# 1. Vector

In [1]:
import numpy as np
import pandas as pd
import altair as alt
alt.themes.enable('dark')

ThemeRegistry.enable('dark')

In [6]:
# 3-dimentional vector
x = np.array([[1],
              [2],
              [3]])

In [5]:
x.shape

(3, 1)

### Add vector

In [8]:
# Add vector
x = y = np.array([[1],
                 [2],
                 [3]])

x+y

array([[2],
       [4],
       [6]])

In [9]:
np.add(x,y)

array([[2],
       [4],
       [6]])

### Vector-scalar multiplication

In [10]:
alpha = 2
x = np.array([[1],
              [2],
              [3]])

alpha * x

array([[2],
       [4],
       [6]])

### Vector-vector multiplication (dot product)
$ x \cdot y = \begin{bmatrix} x_1 \\ x_2 \end{bmatrix}^T \begin{bmatrix} y_1 \\ y_2 \end{bmatrix} = x_1 \times y_1 + x_2 \times y_2$

In [15]:
x = np.array([[-2],
              [2]])
y = np.array([[4],
              [-3]])

np.matmul(x.T, y)   # dot product
x.T @ y             # dot product

array([[-14]])

# 2. Vector space, span, and subspace

Have 8 rules

1. commutativity: $x+y=y+x$
2. associativity: $x+(y+x)=(y+x)+z$
3. unique zero vector such that: $x+0=x ∀ x$
4. ∀ x there is a unique vector x such that $x+−x=0$
5. identity element of scalar multiplication: $1x=x$
6. distributivity of scalar multiplication w.r.t vector addition: $x(y+z)=xz+zy$
7. $x(yz)=(xy)z$
8. $(y+z)x=yx+zx$


array([[-14]])